---
apiVersion: v1
kind: Template
metadata:
  name: keycloak-bench
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: keycloak-bench-${IMAGE_TAG}
  spec:
    backoffLimit: 5
    template:
      spec:
        restartPolicy: Never
        containers:
          - image: ${IMAGE}:${IMAGE_TAG}
            imagePullPolicy: Always
            name: keycloak-bench
parameters:
- name: IMAGE
  value: quay.io/cathaloconnor/keycloak-bench
- name: IMAGE_TAG
  value: 'latest'
  required: true
